### ISSUE TITLE
Quick Subscribe from web3inbox

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/gm-dapp#5]
## Quick Subscribe from web3inbox

Add the GM app to the "explore app" section of web3inbox.
See spec https://github.com/WalletConnect/walletconnect-docs/pull/574

<img width="200" src="https://user-images.githubusercontent.com/116099/227501258-017e4bf8-6f0a-475e-b62f-7429aa6505ce.jpeg">

**Comment by chadyj** [comment]
@llbartekll @Cali93 @bkrem Is this done now?

**Comment by llbartekll** [comment]
@chadyj it's in w3i in ios wallet so I think so
